# Generated by Django 4.2.7 on 2023-11-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SplitWiseApp', '0003_expense_group_admins_group_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='create', to='SplitWiseApp.user'),
        ),
    ]
